courses-completed.html, curriculum-vitae.html, home-town.html, index.html, path-page.html
I edited the footers to remove extra line breaks. I also removed the
/check/referer part of the path to the CSS validator to avoid an error
(mysterious lack of a referer header).
=> footer edits

690-227-stylesheet.css, index.html
I reduced the width of this new image somewhat to avoid stretching it to
fit the width set for the other images.
=> adjusted pic dimensions

690-227-stylesheet.css
I had forgotten to specify all screen sizes when I set the new
dimensions in the CSS for the newly cropped image; I fixed this here.
=> image sizes w/ responsive design

690-227-stylesheet.css, index.html
I fixed the dimensions of a picture so that it is not so distorted. I
also added the correct "last updated/last modified" date on both the CSS
file and the HTML file I updated earlier today.
=> fixed pic dimensions

curriculum-vitae.html
I edited the resume page in response to learning that my articles are no
longer accessible on the MPP webpage; I removed what are now broken
links and took a line out of the Work Samples section accordingly. I
also updated a date for my work at Amara and took out the word "remote"
for those jobs I did remotely since it seems like too much information
in this context.
=> resume updates

ferrerih_qfg_stylesheet.css
I reduced the border size and the border slice percentage. What I am
trying to do here is get rid of an area of the border which is not
covered by the designated border image (or at least, a bit of unwanted
background is visible behind part of this border image).
=> border experiment

ferrerih_qfg_stylesheet.css
I am restoring the border to its original size for comparison and to see
things more clearly, but further reducing the slice percentage, hoping
to further reduce the unwanted bit of border.
=> second border experiment

ferrerih_qfg_stylesheet.css
I made another minor edit to the border rules to fix the slice point.
=> third border edit

ferrerih_qfg_stylesheet.css
I am trying to reduce the height of both the button for the dropdown
menu and the bottom list item in the menu itself, so that these better
fit the dimensions of their background images.
=> dropdown element height changes

ferrerih_qfg_stylesheet.css
I am slightly adjusting the heights again for the li-bottom and button
elements.
=> second adjustment to li-bottom height

ferrerih_qfg_stylesheet.css
I am reducing the heights of the li-bottom element (by reducing the
bottom padding) slightly again at most screen sizes.
=> reducing heights slightly again

marijuana-policy-page-b.html
I again corrected an error caused by referring to external code through
http rather than https.
=> http to https fix

marijuana-policy-page-b.html
I used the HTML5 semantic tag <figcaption> to caption the image, rather
than my previous awkward placement of an image credit in a separate
section from the image.
=> image caption

jquery.mobile-1.4.5.min.css, stylereflow.css
I am hiding the figure caption below a certain width, since its presence
makes the image even smaller and more difficult to read. Next I am
thinking of implementing a popover below this width.
=> figcaption experiment

marijuana-policy-page-b.html, stylereflow.css
I edited the left and right padding for both the table and the .center
section.
=> padding edits

marijuana-policy-page-b.html, stylereflow.css
This is another attempt to affect the padding around the table, this
time by adding a class of "table" to the enclosing section and changing
the CSS rules accordingly.
=> more padding edits

ferrerih_qfg_stylesheet.css, quest-for-glory.html, stylereflow.css
Changed background size for Quest for Glory page, changed figcaption font size rather than hiding for marijuana policy page.
=> Test branch

home-town.html
For the German a-umlaut character I had written &amul; rather than
&auml; so I corrected this.
=> one letter wrong in HTML entity name

home-town.html
I am trying GetElementById rather than GetElementsByName in the
Javascript to locate the canvas element. I also added an API key;
previously I lacked one.
=> API key and canvas edit

home-town.html
The callback parameter is still giving me errors so I have removed it to
see what will happen.
=> removed callback parameter

home-town.html
=> fixed tag error

690-227-stylesheet.css, home-town.html
I am now simply using a div with an id of map-canvas, rather than
attempting a <canvas> element.
=> went back to using div

home-town.html
I zoomed in slightly, fixed the marker's title, and edited the button
text.
=> minor map edits

690-227-stylesheet.css, home-town.html
I made minor updates to the text of the home town page, reset the center
of the map to the same point as the marker, and included another media
query to give the map an intermediate size at certain widths.
=> map updates etc

690-227-stylesheet.css, path-page.html
In line with my other pages, I replaced paragraphs with simple line
breaks. I also fixed the reference to div.flex; what I wanted was
section.flex.
=> fixed section.flex rules and removed paragraphs

690-227-stylesheet.css, path-page.html
Since I am using display:flex, I need each paragraph to be its own
element, otherwise the link elements will be treated as separate
elements along the vertical flex line. So I made them <div>s. I also
fixed the margin so that the flex box will stay centered and be wide
enough.
=> margin and div elements

690-227-stylesheet.css, path-page.html
I made further minor edits to sizes, widths and padding for center, flex
and summary elements.
=> further size/width/padding edits

690-227-stylesheet.css
I removed unnecessary margin rules for the flex element on the path page
at certain screen widths.
=> removed unnecessary margin rules

690-227-stylesheet.css
I removed yet another unnecessary margin rule for the section.flex
element.
=> final margin rule removal

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I added a missing "back to top" link at the end of the first section and
fixed the references to a background image which I had renamed.
=> background image and back to top links

courses-completed.html, curriculum-vitae.html, home-town.html, index.html, marijuana-policy-page-b.html, path-page.html
I corrected the footer so that the "back to top" link is on the same
line as the previous two links; for one thing I believe this prevents my
name from being split into two previous lines. I also fixed a link to my Quest for Glory webpage.
=> footer correction

690-227-stylesheet.css
I increased the width of the footer to fit my name without breaking it
over two lines, and decreased the width of div.left and div.right
elements somewhat on narrower screens.
=> width edits

690-227-stylesheet.css
I forgot to specify that the left and right divs at smaller screen widths need to be
centered.
=> center the left and right divs

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I embedded a video from YouTube of the original game soundtrack and
added some style rules to give it appropriate sizes at different screen
widths.
=> embedded video

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I edited the sizes of the iframe for the embedded video and placed it
above rather than below the text in that section. I also attempted to
center the iframe and display it as a block to avoid text wrapping
around it.
=> edited QFG4 iframe sizes

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I am experimenting in an attempt to get the affix to work and to get the
toolbar to be hidden on load until mouseover. I also made some minor
changes to the text including italicizing titles.
=> trying to fix affix, hide toolbar initially

ferrerih_qfg_stylesheet.css
I made some edits to move the affixed menu to a convenient position on
the right side, hide it altogether at several smaller widths, and get
the dropdown menu to show in the right place when the affix is in
effect.
=> affix edits

ferrerih_qfg_stylesheet.css
I am trying to reverse my accidental hiding of the menu button when the
affix is not in effect by adding a display:block rule.
=> display:block

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I made affix and button display edits.
=> Qf g4 branch

ferrerih_qfg_stylesheet.css
I changed the order of rules so that the .affix block with a
display:none line now comes after rather than before the display:block
rules for buttons.
=> changed order of display values

ferrerih_qfg_stylesheet.css
I moved the main title and game toolbar back slightly to the right by
increasing the left offset at the highest screen width. I also moved the
main title to the left at the smallest screen size to avoid going off
the right edge of the screen.
=> header positioning

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I added an extra picture to the carousel and improved the text
descriptions in the music and introductory sections.
=> extra picture, text edits, remove JQuery

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I had done a search-and-replace to add spaces after all colons to adhere
to the standard for CSS name-value pairs but had forgotten that this
would affect pseudoclasses, so here I corrected the pseudoclasses.
=> fixed pseudoclass error

ferrerih_qfg_stylesheet.css
I corrected another error in the CSS pseudoclasses involving unnecessary
spaces.
=> corrected one more pseudoclass error

ferrerih_qfg_stylesheet.css
I located and fixed one more error in the CSS pseudoclasses.
=> fixed one more pseudoclass error

ferrerih_qfg_stylesheet.css
I corrected the background color of the button so that the transparent
border which seems to activate on clicking would no longer appear blue.
=> button border correction

ferrerih_qfg_stylesheet.css
Here I am replacing display:none with visbility:hidden, a similar but
not identical name-value pair. This is again trying to fix the bug where
the menu button is invisible after scrolling down and scrolling back up.
=> another menu fix attempt with visibility

ferrerih_qfg_stylesheet.css, quest-for-glory.html
I am fixing the visibility value at larger screen widths to make the
menu button visible there in the affix state. I also removed what is now
superfluous (and unsuccessful) attempts at JQuery affecting visibility.
=> one more fix to menu button visibility

quest-for-glory.html
I improved the text somewhat, including links to more external resources
such as a help page, a hint book and an old review.
=> text improvements

quest-for-glory.html
slight changes to text in downloads section regarding Hero U and Hero 6
=> minor downloads edits

marijuana-policy-page-b.html
I updated the last modified date in the <meta> description tag.
=> updated last modified date

marijuana-policy-page-b.html
=> Marijuana updates

path-page.html
Added description of my current job, added reference to aesthetics,
updated one link and added others, fixed indentation.
=> updated text, links, indentation

quest-for-glory.html
These changes actually belonged on QfG4-branch.
=> Path page updates

courses-completed.html, curriculum-vitae.html
updates to the courses and curriculum vitae pages
=> Further home page updates

curriculum-vitae.html
I updated a few links to organizations I have previously worked with,
including specifying secure connections where possible.
=> updated links

curriculum-vitae.html
Somehow I managed to write an ä where I intended a ü; I have corrected
this.
=> corrected German letter

quest-for-glory.html
I edited the last-updated date and added another paragraph break.
=> minor text corrections

quest-for-glory.html
Updated information on Hero-U project.
=> Qfg4 branch

path-page.html
I made minor edits to the text including adding more paragraph breaks.
=> edited text

path-page.html
I took my psychologist's suggestions on making my path page less
self-deprecating and less verbose.
=> took psychologist's recommendations

ferrerih_p2_access_altered.php, ferrerih_p2_browse.php, ferrerih_p2_stylesheet.css
Added files used for assignment for grad school course Web Databases, displaying scientific journal articles. None of this works anymore; I no longer have access to the relevant databases as I have not been a student for some time.
=> files from grad school Web Databases course

ferrerih_p3_access_altered.php, ferrerih_p4_results.php, ferrerih_p4_stylesheet.css, keyword-suggestions.php, result-details.php
Added files used for video search project from Web Databases grad school course, with updated explanatory notes.
=> files from another Web Databases project

quest-for-glory.html
Updated to reflect fact that Hero-U game is now available.
Also shortened a few lines based on the general rule of avoiding lines longer than 120 characters.
=> updated re: new game, shortened lines

marijuana-policy-page-b.html, quest-for-glory.html
Updated references to jQuery to refer to the latest version.
=> updated jQuery references

quest-for-glory.html
I updated the references in the Quest for Glory page to Bootstrap and jQuery to refer to newer versions and added another Javascript file needed for Bootstrap functionality.
=> updated Bootstrap and jQuery scripts

quest-for-glory.html
Switched to Bootstrap 3, which does not cause the kind of problems Bootstrap 4 did.
=> Script updates

ferrerih_qfg_stylesheet.css
I removed references in the stylesheet to a font type I had never successfully used and had already deleted the files for.
=> updated stylesheet re: fonts

quest-for-glory.html
I updated from master and also changed the version of jQuery to 2.2.4 in order to avoid an error message from Bootstrap.
=> Quest for glory

marijuana-policy-page-b.html
Update the email link in the footer to my new Protonmail address.
=> update email link

quest-for-glory-de.html, quest-for-glory.html
For SEO purposes, make sure links contain text describing their targets instead of terms like "here."
=> ensure descriptive links

index.html
Add descriptive links for SEO purposes, replacing hypertext like "this" and "here."
=> add descriptive links

marijuana-policy-page-b.html
Add a link to my homepage so that the page is not a "dead end."
=> add link to homepage

marijuana-policy-page-b.html
Update table to show North Dakota has decriminalized marijuana.
=> Update North Dakota

marijuana-policy-page-b.html
Update outdated current laws links, fix misdirected link from North Dakota row to North Carolina page.
=> Marijuana policy updates

courses-completed.html, curriculum-vitae.html, home-town.html, index.html, marijuana-policy-page-b.html, path-page.html
Expand descriptions in meta tags for SEO purposes.
=> improve meta descriptions

curriculum-vitae.html
Update curriculum vitae with reference to a WillowTree project for prospective employees I am working on.
=> add reference to WillowTree project

quest-for-glory-de.html, quest-for-glory.html
Remove the second meta description tag with the last-modified date; this gives an error in HTML validation.
=> remove extra meta description

courses-completed.html, curriculum-vitae.html, home-town.html, index.html, path-page.html
Remove last modified date from meta description, add link and meta modified tag referencing Dublin Core.
=> improve last modified info

690-227-stylesheet.css, index.html
Improve color scheme and borders. Add outset borders to section elements, buttons and title. Add gold as a background color for sections. Add blue and brown as link colors in sections and add a gradient background for title.
=> Fix CSS styling

marijuana-policy-page-b.html
Clarify a reference to the table and a reference to an event in 2018. Also update a link to my writing.
=> minor text updates

marijuana-policy-page-b.html
Update information re: decriminalization in VA and legalization in Maine and Illinois. Also improve notes.
=> Marijuana page

marijuana-policy-page-b.html
Update status of legalization bill in Vermont.
=> Update text re: Vermont

690-227-stylesheet.css, path-page.html
Update text for career path page to refer to current and recent employment. Also update HTML and CSS to display paragraphs properly.
=> Update text and CSS for path page

690-227-stylesheet.css
Alter the CSS to give the borders of the navbar items and the summary div a consistent color. Correct the border width of the summary div.
=> Fix border color and width

courses-completed.html, curriculum-vitae.html, home-town.html, index.html, marijuana-policy-page-b.html, path-page.html
Update the copyright and last updated dates.
=> Update copyright and last updated dates

marijuana-policy-page-b.html
Correct reference in table to VA decriminalization bill. Bill has been sent back to legislature with amendments; not yet finally approved.
=> Corrected table re: VA decrim.

ferrerih_qfg_stylesheet.css
Fix stylesheet reference to new background image.
=> Fix stylesheet

googled9ea1c3b4c510ed3.html
Add the tag to connect this page to Google Search Console.
=> Add Google Search Console tag

quest-for-glory-de.html
Reflect the latest changes to the image formats in the German version.
=> Update German version with image changes

quest-for-glory-de.html, quest-for-glory.html
Set the Bootstrap Javascript to be asynchronous to speed up loading.
=> Make Bootstrap Javascript asynchronous

ferrerih_qfg_stylesheet.css
Change the height of some of the menu images in the carousel. Also change the width to maintain the same proportions.
=> Fix height of some carousel menu images

marijuana-policy-page-b.html
Update the main text to reflect recent legalization measures in NM, VA and NY and federal legalization bill under consideration.
=> Update text to reflect recent changes

marijuana-policy-page-b.html
Use the latest version of jQuery, 3.6.0.
=> Use latest version of jQuery

marijuana-policy-page-b.html
Reverts bdferr/bdferr.github.io#199
=> Revert "Use latest version of jQuery"

marijuana-policy-page-b.html
Fix error in link under Maine note.
=> Marijuana policy

jquery.mobile-1.4.5.min.css, stylereflow.css
Remove unused style rules from CSS.
=> Remove unused CSS

stylereflow.css
Change width of elements to better fit size of content.
=> Fix width of elements

quest-for-glory-de.html, quest-for-glory.html
Remove text reference to YouTube video which is no longer embedded.
=> Remove reference to video

quest-for-glory-de.html, quest-for-glory.html
Make minor improvements to text; describe plot, separate paragraphs, improve wording.
=> Improve text

ferrerih_qfg_stylesheet.css
Remove unnecessary comments from CSS.
=> clean up CSS

ferrerih_qfg_stylesheet.css
Change the CSS for the h1 element on non-mobile screen widths to match the style of the body.
=> Fix main title CSS

home-town.html
Fix errors in outbound links. Quotes were out of place.
=> Fix link errors

ferrerih_qfg_stylesheet.css
Fix position of carousel indicators so they do not obscure images at smaller screen widths.
=> Fix carousel indicators

curriculum-vitae.html
Add new link to W3Schools certifications for web skills.
=> Add updated link to W3Schools certifications

marijuana-policy-page-b.html
Fix homepage link in footer to lead to the right page.
=> Fix link to homepage

quest-for-glory-de.html, quest-for-glory.html
Make minor fixes to wording of text.
=> fix wording

ferrerih_qfg3_stylesheet.css
Shift the heading upwards to remove a gap between it and the top menu bar. Also move the button upwards accordingly.
=> Adjust position of heading and button

ferrerih_qfg3_stylesheet.css
Adjust positions of dropdown button and menu in affix position.
=> Adjust affix positions

ferrerih_qfg_stylesheet.css, quest-for-glory-de.html, quest-for-glory.html
Reintroduce old pixelated font Pixelar as second choice when Quest for Glory IV font fails.
=> Bring back old font as backup

ferrerih_qfg3_stylesheet.css
Set position of toolbar to accommodate Rakeesh image and wider screens.
=> Change position of toolbar

ferrerih_qfg3_stylesheet.css
Edit padding and dimensions of footer.
=> More edits to QFG3 footer

ferrerih_qfg3_stylesheet.css
Change placement of QfG3 button in affix position.
=> Change placement of affixed button

ferrerih_qfg1_stylesheet.css, ferrerih_qfg3_stylesheet.css, ferrerih_qfg_stylesheet.css
Move font-face block for Quest for Glory font to top of stylesheet.
=> move font-face block to top of stylesheet

ferrerih_qfg1_stylesheet.css
Implement icons from the game as cursors.
=> implement icons as cursors

quest-for-glory1.html
Add paragraph to main text section explaining new night mode.
=> Add text explaining night mode

quest-for-glory1.html
Use jQuery to fix bug which caused menu button initial background image to disappear upon clicking.
=> Fix menu button display bug

ferrerih_qfg1_stylesheet.css, ferrerih_qfg3_stylesheet.css
Implement QfG3 scarab waiting icon as the cursor for the header.
=> implement scarab cursor

ferrerih_qfg3_stylesheet.css, quest-for-glory3.html
Add two more pairs of QfG3 icons to the Icons section.
=> Add more icons to main text

ferrerih_qfg1_stylesheet.css
Reduce the top padding of the top item in the QfG1 menu to increase distance between it and the following item.
=> fix padding of top element in QfG1 menu

ferrerih_qfg1_stylesheet.css
Reduce the width of QfG1 menu items on the narrowest screens, i.e. mobile devices.
=> fix width of QfG1 menu on mobile devices

ferrerih_qfg1_stylesheet.css, ferrerih_qfg3_stylesheet.css, ferrerih_qfg_stylesheet.css
Fix z-index of carousel indicators so that they do not appear in front of dropdown menu on narrow screens.
=> Revert "Revert "Fix z-index of carousel indicators""

ferrerih_qfg1_stylesheet.css, quest-for-glory1.html
Set the text of a highlighted item in the menu to have a different color in night mode.
=> Change night mode highlighted menu text color

quest-for-glory1.html
Fix jQuery on QfG1 page to implement new higher-quality menu bar image when changing from night to day mode.
=> Fix jQuery to reflect new menu bar image

qfg1_stylesheet.css, qfg4_stylesheet.css, quest-for-glory1.html
Implement night mode on QfG1 page regarding cursors.
=> Implement night mode on cursors

qfg1_stylesheet.css
Fix CSS reference to Quest for Glory font for use on QfG1 page.
=> fix reference to gloryquest font

qfg4_stylesheet.css, quest-for-glory4-de.html, quest-for-glory4.html
Add more icons to the QfG4 icon section and arrange them in a row rather than a column.
=> Further improve icon section

quest-for-glory1.html, quest-for-glory3.html, quest-for-glory4.html
Improve the downloads section of the QfG pages, removing references to lower-quality spinoffs and adding more information about Heroine's Quest.
=> improve Downloads section text

quest-for-glory4-de.html, quest-for-glory4.html
Fix links to and from German version of QfG4 page.
=> fix links to/from QfG4 German version

quest-for-glory4-de.html
Change the German version of the QfG4 page to reflect recent changes to the English page. This includes id of feet icon on menu button, main text, and one updated link.
=> reflect recent changes to English page on German page

quest-for-glory4-de.html
Fix the filename reference to the toolbar image on the German page to reflect recent change to file format.
=> Fix reference to toolbar image on German QfG4 page

quest-for-glory4-de.html
Add link to QfG1 page from German QfG4 page.
=> add reference to QfG1 from German page

quest-for-glory4-de.html
Fix id and classes in menu item linking to QfG1 page from QfG4 German page.
=> Fix id and classes in QfG1 link

qfg1_stylesheet.css
Add padding for the narrowest screen widths (mobile devices) in the main text of the QfG1 page.
=> QFG1: Add padding on mobile devices

qfg3_stylesheet.css
Fix CSS reference to QfG3 background image; file format has changed.
=> Fix CSS reference to QfG3 background image

qfg3_stylesheet.css
Adjust CSS for the border on the QfG3 main text to more accurately reflect the original image.
=> Fix border on QfG3 main text

quest-for-glory1.html, quest-for-glory3.html, quest-for-glory4-de.html, quest-for-glory4.html
Remove an extra reference to QfG cursors being implemented as extensions to an operating system; this is already mentioned under Icons.
=> Remove extra text

quest-for-glory1.html, quest-for-glory3.html
Improve the text in the Icons section to clarify re: the waiting icons.
=> Improve text under Icons

quest-for-glory1.html
Expand the generic alt text on the QfG1 icons to be more specific.
=> improve QfG1 alt text

qfg1_stylesheet.css
Change the color of the text in the links which select QfG1 day/night mode.
=> Change day/night mode link text

qfg3_stylesheet.css, quest-for-glory3.html
Apply night mode to cursors on QfG3 page.
=> Implement night mode for QfG3 cursors

qfg3_stylesheet.css, quest-for-glory3.html
Alter padding and border of main text to fit different screen widths for QfG3 page in night mode.
=> Edit QfG3 nighttime padding and border for different screen widths

quest-for-glory1.html, quest-for-glory3.html
Edit text in Downloads section for QfG1 and QfG3 to remove reference to QfG4 mod. Include link to its creator's website in previous paragraph.
=> Edit Downloads text for QfG1 and QfG3

quest-for-glory4-de.html, quest-for-glory4.html
Fix the reference to the QfG4 feet icon in the Icons section of the text to reflect recent change in filename.
=> Fix reference to QfG4 feet icon in text

qfg1_stylesheet.css, qfg3_stylesheet.css, qfg4_stylesheet.css
Remove the rounded corners on menu buttons. Replace with sharp corners to match all other elements.
=> Remove rounded corners on menu buttons

qfg4_stylesheet.css
Fix reference in QfG4 stylesheet to recently changed filename for icon used when mousing over heading.
=> Fix QfG4 CSS for icon

quest-for-glory4-de.html, quest-for-glory4.html
Update the release date for the latest upcoming Hero-U game on QfG4 pages.
=> Update release date for game

quest-for-glory3.html
Add paragraph break under QfG3 Icons section to match Icons section on other pages.
=> Add paragraph break under QfG3 Icons

quest-for-glory4-de.html, quest-for-glory4-it.html, quest-for-glory4.html
Add Italian version of QfG4 page.
=> Add Italian version of QfG4 page

quest-for-glory4-it.html
Fix misspelling in Italian version of QfG4 page.
=> Fix Italian QfG4 typo

quest-for-glory4-it.html
Fix error in gender of past participle of "called" on QfG4 Italian page.
=> Fix Italian grammatical error

quest-for-glory4-it.html
Fix a typo in the word for "while" in the Italian QfG4 page.
=> Fix another Italian typo

qfg4_stylesheet.css
Specify text shadow in CSS based on original game text.
=> Add text shadow to QfG4 page

quest-for-glory4-it.html
Correct two errors in Italian vocabulary on QfG4 page.
=> Correct errors in Italian QfG4 text

qfg4_stylesheet.css, quest-for-glory4-de.html, quest-for-glory4-it.html, quest-for-glory4.html
Set cursor to be hand icon when mousing over language options in footer.
=> Set cursor to hand for language options

quest-for-glory4-it.html
Correct grammatical error on QfG4 Italian page.
=> Correct QfG4 Italian error

qfg1_stylesheet.css, qfg3_stylesheet.css, qfg4_stylesheet.css
Change CSS to set position: absolute for QfG menu bar. This fixes error in position of menu bar when user scrolls down and mouses over header.
=> Fix QfG menu bar bug

qfg-book.html, qfg_book_stylesheet.css
Add text  noting that page is under construction so submitting email addresses does not work yet.
=> Add under construction note to QfG book page

qfg_book_stylesheet.css
Add thicker borders on the subscribe button and text box to fit with low-resolution style.
=> Thicker borders on QfG book page form elements

qfg_book_stylesheet.css
Italicize the name of the book on the QfG book page.
=> Italicize QfG book name

qfg_book_stylesheet.css
Change CSS for email input box to specify that border remains the same when clicked on.
=> alter CSS for QfG book email input

qfg3_stylesheet.css
Add initial slash to path referring to embedded font for QfG3 page.
=> Add initial slash to QfG3 embedded font reference

qfg-book.html, qfg_book_stylesheet.css
Adjust CSS and HTML on QfG book page to fit narrower screens.
=> Adjust QfG book page layout for narrower screens

qfg-book.html
Add Javascript and HTML to QfG book page so that submitted email addresses can be added to the Mailchimp list. Remove under construction note now that this function is working.
=> Add QfG book page code to process email addresses

qfg3_stylesheet.css, quest-for-glory3.html
Add crude time and date box to QfG3 page with toggle button in footer.
=> Introduce QfG3 time and date box

qfg3_stylesheet.css, quest-for-glory3.html
Adjust the new time/date function to fit with day and night mode on the QfG3 page. Display different images depending on whether the page is in day or night mode. Adjust CSS and jQuery accordingly.
=> Time/date adjustments for QfG3 day/night mode

qfg3_stylesheet.css
Reduce z-index of QfG3 toolbar so that it does not cover date/time box.
=> Fix z-index of QfG3 toolbar

quest-for-glory3.html
Add code to get current date and time and format it correctly.
=> Add code to get current date & time

qfg3_stylesheet.css
Adjust size and positioning of time/date box based on screen width.
=> make size and positioning of time/date box responsive

qfg3_stylesheet.css, quest-for-glory3.html
Correct the color of links in the footer on mouseover.
=> QfG3 page: correct color of footer links on mouseover 

qfg3_stylesheet.css
Add a shadow to the date/time box.
=> Add shadow to QfG3 date/time box

quest-for-glory3.html
Remove code recording time/date to console; only needed for testing.
=> Remove QfG3 time/date testing statement

qfg3_stylesheet.css, quest-for-glory3.html
Fix capitalization error in reference to file used for QfG3 carousel image.
=> Fix QfG3 image file capitalization error

qfg3_stylesheet.css, quest-for-glory3.html
Fix CSS and jQuery so that QfG3 carousel controls (left and right arrows) have correct colors for day and night mode.
=> Fix color of QfG3 carousel controls

qfg3_stylesheet.css
Adjust positioning of QfG3 carousel indicators.
=> Adjust position of QfG3 carousel indicators

quest-for-glory3.html
Break up nighttime screenshots on QfG3 carousel by adding new daytime image and changing order of images.
=> Improve QfG3 carousel

qfg3_stylesheet.css
Remove the top and bottom padding in the main text in QfG3 night mode.
=> Remove top/bottom padding in QfG3 night mode

qfg1_stylesheet.css
Adjust position of carousel indicators downwards on narrowest screens (mobile devices).
=> Adjust carousel indicators for mobile

qfg3_stylesheet.css, quest-for-glory3.html
Change the jQuery so that switching from night to day mode makes the image of Rakeesh visible only on sufficiently wide screens.
=> alter QfG3 jQuery re: Rakeesh

quest-for-glory4-de.html, quest-for-glory4-it.html
Implement time/date box on German and Italian versions of QfG4 page.
=> Implement time/date box on German, Italian pages

quest-for-glory4-it.html
Fix minor errors in word choice/grammar in Italian version of QfG4 page.
=> Fix QfG4 Italian errors

quest-for-glory1.html, quest-for-glory3.html, quest-for-glory4.html
Update text re: upcoming game from creators of Quest for Glory.
=> update game info

qfg3_stylesheet.css, quest-for-glory3.html
Adjust positioning of text and image in QfG3 dropdown menu button on wider screens.
=> adjust elements in QfG3 menu button

qfg1_stylesheet.css
Hide QfG1 running man icon in menu button on narrower screens.
=> hide QfG1 menu image on narrower screens

quest-for-glory4-de.html, quest-for-glory4-it.html
Update the German and Italian versions of the QfG4 page re: the new game which is "coming soon."
=> update German and Italian

quest-for-glory4-de.html, quest-for-glory4-it.html, quest-for-glory4.html
Update outdated link to track from QfG4 soundtrack.
=> update QfG4 music link

qfg3_stylesheet.css, quest-for-glory3.html
Set a single height at each screen width for QfG3 carousel images.
=> set QfG3 carousel image height

qfg4_stylesheet.css, quest-for-glory4-de.html, quest-for-glory4-it.html, quest-for-glory4.html
Replace numerous ids for QfG4 carousel images with a single CSS class.
=> simplify QfG4 CSS

marijuana-policy-page-b.html
Update text to reflect recent changes to state marijuana laws.
=> update text re: latest state marijuana laws

quest-for-glory4-de.html, quest-for-glory4-it.html, quest-for-glory4.html
Update text on QfG4 page re: recently released game in new series.
=> update references to new game

quest-for-glory4-de.html
Correct minor errors in vocabulary and grammar in German text.
=> correct QfG4 German text

quest-for-glory1.html
Fix error in carousel causing wrong slide to appear first on loading.
=> fix carousel error

quest-for-glory1.html, quest-for-glory3.html, quest-for-glory4-de.html, quest-for-glory4-it.html
Update links and text regarding newly available game in Hero-U series.
=> update links and text re: new game

quest-for-glory4-de.html, quest-for-glory4-it.html, quest-for-glory4.html
Update broken link re: critics' assessment.
=> fix broken link

quest-for-glory4-it.html
Make various corrections in the Italian QfG4 text.
=> Correct Italian text
