bdferr/bdferr.github.io

ferrerih_qfg_stylesheet.css
quest-for-glory.html

I had an element within a footer which was also labeled as a "footer,"
but by class rather than element name. This seemed wrong what with the
semantic HTML5 element having replaced the earlier <div class="footer"> option
so I changed it to "footer-note."

changed "footer" class to "footer-note"

---

stylereflow.css

The ```<figure>``` element had an unnecessary margin so I made rules
specifying zero margin.

fixed figure margin

---

home-town.html

I am changing the callback function from initialize to initMap in
accordance with the instructions from Google Developers and an error
message complaining that initialize is "not a function."

initialize vs initmap function in callback

---

690-227-stylesheet.css

For some elements on the path page, I set the font size, width and
padding to the same as those of section.center at some screen widths.

font size and padding on path page

---

quest-for-glory.html

For the moment I have edited the JQuery so that mousing over the title
ensures that the menu button is visible. Clicking on a back to top
button should now do the same thing. This gets around the problem of the
menu button, having disappeared at the affix point, not reappearing when
scrolling back to the top of the page.

jQuery workaround

---

quest-for-glory.html

I fixed a reference to Hero6, both to remove the space from "Hero 6" and
to fix the link to a more up-to-date source, namely the game's website
rather than a Quest for More Glory forum.

fixed reference to Hero6

---

marijuana-policy-page-b.html
quest-for-glory.html

Reverts bdferr/bdferr.github.io#111
This had created a conflict between the old version of Bootstrap and the newer version of jQuery, and also between the newer version of jQuery and the older version of jQuery mobile.

Revert "updated jQuery references"

---

ferrerih_qfg_stylesheet.css

By changing all references to the #game-toolbar element's "max-width" to "width," I fixed the slideup() and slidedown() functionality for the game toolbar image. Previously it had grown and shrunk diagonally rather than only up and down as it now does.

fixed slideup() and slidedown() for toolbar

---

ferrerih_qfg_stylesheet.css
quest-for-glory.html

I made the navigation menu visible in the affix position at every media query; previously it had only been visible at wider widths. I made adjustments to accommodate this including moving the navigation anchors for each section to the "back to top notes" immediately above them so that the user could navigate to a section using the menu without the menu button then covering up the section heading.

Quest for glory

---

ferrerih_qfg_stylesheet.css
quest-for-glory-de.html
quest-for-glory.html

Change the CSS rules regarding the main background image to fix a scrolling bug. It had been set to "fixed" but had not rendered that way on a mobile device.
Also expand the background to fill the whole width of the screen and set Dr. Cranium to only appear when the screen is wide enough that his head will not be blocked by the title.

fix CSS rules re: background

---

ferrerih_qfg_stylesheet.css

Alter the padding and font size in the h1 heading to better fit the element's background image.

Fix padding and font size in header

---

ferrerih_qfg_stylesheet.css

Remove CSS rules referring to iframe no longer in use for embedded YouTube video.

Remove unused CSS

---

ferrerih_qfg3_stylesheet.css

Add margin at bottom of carousel to give more space to "back to top link." Adjust carousel indicators to compensate.

adjust carousel indicators and back to top link

---

ferrerih_qfg3_stylesheet.css

Add top and bottom margins to QfG3 icons displayed in Icons section; make less crowded.

add margins to icons

---

quest-for-glory3.html

Edit text in Icons section to explain that icons look different depending on time of day. Change reference to walking icon in navigation menu because this is only displayed at larger screen widths.

improve text under Icons

---

ferrerih_qfg1_stylesheet.css

Fix error in padding adjustments for QfG1 menu items. Again this is to make sure highlighted area on mouseover fits well within menu border regardless of screen width.

fix padding for menu items again

---

quest-for-glory1.html
quest-for-glory3.html
quest-for-glory4.html

Edit the Downloads section text of QfG1 and QfG3 pages to remove text/links specific to QfG4, replace with content specific to QfG1 and QfG3. Replace link to archived version of QfG4 hint book with link to current Sierragamers.com page.

improve Downloads sections

---

quest-for-glory1.html

Add daytime CSS class to links in QfG1 HTML so that it is applied without toggling day/night mode. Do the same with carousel controls.

add daytime class to elements by default

---

qfg1_stylesheet.css

Change the color of the QfG1 carousel indicators to dark brown to match the links in the text.

Change QfG1 carousel indicator color

---

qfg1_stylesheet.css

Change carousel controls to dark brown when mousing over. This is to match links and carousel indicators.

Change hover color of carousel controls

---

qfg1_stylesheet.css
qfg3_stylesheet.css

Fix color for QfG1 carousel indicators in night mode to match carousel controls. Also remove superfluous CSS.

Fix color for QfG1 nighttime carousel indicators

---

qfg_book_stylesheet.css

On QfG book page, change color of links when mousing over them from blue to cyan for better readability.

Change QfG book page link hover color

---

qfg_book_stylesheet.css

Set cursor to the same sword icon used elsewhere on the page for the label element in the form.

Set cursor to QfG1 sword icon over form label

---

qfg3_stylesheet.css

Alter CSS to change size & position of text for time/date box on narrow screens (mobile devices). Also correct size of background image for narrow screens.

Adjust QfG3 time/date box for mobile

---

quest-for-glory3.html

Remove the blank "id" attributes from the images in the QfG3 carousel.

QfG3 page: Remove blank id attributes

---

qfg3_stylesheet.css

Hide QfG3 walking icon in dropdown menu button on narrower screens.

hide QfG3 menu image on narrower screens

---

quest-for-glory3.html
quest-for-glory4-de.html
quest-for-glory4-it.html
quest-for-glory4.html

Remove seconds from time and date displays on QfG3 and QfG4 pages. Also update copyright dates in footers.

simplify time and date
